import 'dart:async';
import 'dart:typed_data';
import 'package:typed_isolate/typed_isolate.dart';

import '../core/llama.dart';
import '../core/llama_input.dart';
import '../core/llama_log_level.dart';
import '../prompt/prompt_format.dart';
import 'isolate_child.dart';
import 'isolate_scope.dart';
import 'isolate_types.dart';

/// Thrown to the awaiter of a pending [LlamaParent] operation when a newer
/// operation supersedes it (e.g. a `clear()` issued while a model load or an
/// in-flight `stop()` has not yet been confirmed by the child isolate).
///
/// Superseding is a NORMAL condition during teardown/recovery: the message
/// preserves the legacy `'Operation superseded by: <description>'` text so
/// callers that duck-type on the string keep working across the fork bump.
/// Callers awaiting an operation that can legitimately be superseded (stop,
/// clear, dispose/unload, the load-attempt ladder) should catch this and treat
/// it as benign cancellation rather than a fatal error.
class LlamaSupersededException implements Exception {
  /// Description of the operation that superseded the pending one.
  final String supersededBy;
  LlamaSupersededException(this.supersededBy);

  /// Kept byte-compatible with the previous `StateError` toString so existing
  /// string matches (`.contains('Operation superseded')`) still fire.
  @override
  String toString() => 'Operation superseded by: $supersededBy';
}

/// Event emitted when a completion finishes or fails
class CompletionEvent {
  final String promptId;
  final bool success;
  final String? errorDetails;
  CompletionEvent(this.promptId, this.success, [this.errorDetails]);
}

/// Structure to hold queued prompts
class _QueuedPrompt {
  final String prompt;
  final Completer<String> idCompleter = Completer<String>();
  final Object? scope;
  final List<LlamaImage>? images;
  final String? grammarStr;
  final String? grammarRoot;
  _QueuedPrompt(this.prompt, this.scope,
      {this.images, this.grammarStr, this.grammarRoot});
}

/// Parent class that manages communication with the LlamaChild isolate
class LlamaParent {
  final StreamController<String> _controller = StreamController<String>.broadcast();
  final _parent = IsolateParent<LlamaCommand, LlamaResponse>();

  StreamSubscription<LlamaResponse>? _subscription;
  bool _isGenerating = false;
  LlamaStatus _status = LlamaStatus.uninitialized;
  LlamaStatus get status => _status;

  /// List of messages for chat history used by the formatter
  List<Map<String, dynamic>> messages = [];

  final LlamaLoad loadCommand;
  final PromptFormat? formatter;

  Completer<void>? _readyCompleter;
  Completer<void>? _operationCompleter;
  Completer<List<double>>? _embeddingsCompleter;
  Completer<int>? _tokenizeCompleter;

  Completer<Uint8List>? _stateCompleter;

  /// Maps prompt IDs to completers for operation tracking
  final Map<String, Completer<void>> _promptCompleters = {};

  /// Stream of text generated by the model
  Stream<String> get stream => _controller.stream;

  /// Whether text generation is in progress
  bool get isGenerating => _isGenerating;

  final _completionController = StreamController<CompletionEvent>.broadcast();
  Stream<CompletionEvent> get completions => _completionController.stream;

  String _currentPromptId = "";
  final List<dynamic> _scopes = [];
  final List<_QueuedPrompt> _promptQueue = [];
  bool _isProcessingQueue = false;

  Object? _currentScope;

  LlamaParent(this.loadCommand, [this.formatter]);

  Future<void> init() async {
    _readyCompleter = Completer<void>();
    _isGenerating = false;
    _status = LlamaStatus.uninitialized;

    _parent.init();
    await _subscription?.cancel();
    _subscription = _parent.stream.listen(_onData);

    await _parent.spawn(LlamaChild());

    await _sendCommand(LlamaInit(Llama.libraryPath), "library initialization");

    _status = LlamaStatus.loading;
    await _sendCommand(loadCommand, "model loading");

    await _readyCompleter!.future;
  }

  void _onData(LlamaResponse data) {
    if (data.stateData != null) {
      if (_stateCompleter != null && !_stateCompleter!.isCompleted) {
        _stateCompleter!.complete(data.stateData);
        _stateCompleter = null;
      }
      return; 
    }

    if (data.embeddings != null) {
      if (_embeddingsCompleter != null && !_embeddingsCompleter!.isCompleted) {
        _embeddingsCompleter!.complete(data.embeddings);
        _embeddingsCompleter = null;
      }
      return;
    }

    if (data.tokenCount != null) {
      if (_tokenizeCompleter != null && !_tokenizeCompleter!.isCompleted) {
        _tokenizeCompleter!.complete(data.tokenCount);
        _tokenizeCompleter = null;
      }
      return;
    }

    if (data.status == LlamaStatus.error && data.errorDetails != null) {
      final ex = LlamaException(data.errorDetails!);
      
      if (_operationCompleter != null && !_operationCompleter!.isCompleted) {
        _operationCompleter!.completeError(ex);
        _operationCompleter = null;
      }
      if (_stateCompleter != null && !_stateCompleter!.isCompleted) {
        _stateCompleter!.completeError(ex);
        _stateCompleter = null;
      }
      if (_tokenizeCompleter != null && !_tokenizeCompleter!.isCompleted) {
        _tokenizeCompleter!.completeError(ex);
        _tokenizeCompleter = null;
      }
    }

    if (data.status != null) {
      _status = data.status!;
      if (data.status == LlamaStatus.ready &&
          _readyCompleter != null &&
          !_readyCompleter!.isCompleted) {
        _readyCompleter!.complete();
      }
    }

    if (data.isConfirmation) {
      if (_operationCompleter != null && !_operationCompleter!.isCompleted) {
        _operationCompleter!.complete();
      }
    }

    if (data.text.isNotEmpty) {
      // Defensive isClosed check: dispose() may have closed the controller in
      // a different microtask while the child was still flushing tokens.
      if (!_controller.isClosed) {
        _controller.add(data.text);
      }
      for (final scope in _scopes) {
        scope.handleResponse(data);
      }
    }

    if (data.isDone && data.stateData == null && data.embeddings == null && !data.isConfirmation) {
      _isGenerating = false;
      final promptId = data.promptId ?? _currentPromptId;

      if (_promptCompleters.containsKey(promptId)) {
        if (!_promptCompleters[promptId]!.isCompleted) {
          _promptCompleters[promptId]!.complete();
        }
        _promptCompleters.remove(promptId);
      }

      final success = data.status != LlamaStatus.error;
      final event = CompletionEvent(promptId, success, data.errorDetails);

      // Defensive isClosed check: see comment on _controller.add above.
      if (!_completionController.isClosed) {
        _completionController.add(event);
      }
      for (final scope in _scopes) {
        scope.handleCompletion(event);
      }
      _currentScope = null;
    }
  }

  /// Requests the child to save the VRAM state of a specific scope to RAM.
  Future<Uint8List> saveState(LlamaScope scope) async {
    _stateCompleter = Completer<Uint8List>();
    _parent.sendToChild(id: 1, data: LlamaSaveState(scope.id));
    
    return _stateCompleter!.future.timeout(
      const Duration(seconds: 30),
      onTimeout: () {
        _stateCompleter = null;
        throw TimeoutException("Save state timed out");
      }
    );
  }

  /// Requests the child to load RAM state into a VRAM slot.
  Future<void> loadState(LlamaScope scope, Uint8List data) async {
    await _sendCommand(LlamaLoadState(scope.id, data), "load state");
  }

  /// Requests the child to load a Disk session into a VRAM slot.
  Future<void> loadSession(LlamaScope scope, String path) async {
    await _sendCommand(LlamaLoadSession(scope.id, path), "load session");
  }

  /// Requests the child to free the C++ slot associated with this scope.
  Future<void> disposeScope(LlamaScope scope) async {
    // Ensure any pending or in-flight prompts for this scope are stopped before
    // releasing its native slot.
    await cancelScope(scope, cancelInFlight: true, cancelQueued: true);
    _scopes.remove(scope);
    await _sendCommand(LlamaFreeSlot(scope.id), "free slot");
  }

  Future<void> _sendCommand(LlamaCommand command, String description) async {
    // If a previous _sendCommand is still pending (e.g. because the caller
    // issued a clear() while a load was in flight), supersede it with an
    // explicit error instead of silently dropping its completer. Without this,
    // the previous future would only resolve via its 30s/60s timeout.
    final previous = _operationCompleter;
    if (previous != null && !previous.isCompleted) {
      // Defense in depth against the superseded error surfacing as an
      // UNHANDLED async error (Crashlytics: fatal 'Bad state: Operation
      // superseded by: context clear'). A live awaiter keeps its own listener
      // on `previous.future` and still receives the exception below; ignore()
      // only attaches a benign no-op error listener so that a detached awaiter
      // (its .timeout already fired, or a fire-and-forget caller) can never
      // leave the future error-listener-less. It does NOT swallow the error
      // for live awaiters.
      previous.future.ignore();
      previous.completeError(
        LlamaSupersededException(description),
      );
    }
    _operationCompleter = Completer<void>();
    final current = _operationCompleter!;
    _parent.sendToChild(data: command, id: 1);

    return await current.future.timeout(
      Duration(seconds: description == "model loading" ? 60 : 30),
      onTimeout: () {
        if (command is LlamaStop) {
          LlamaLogger.warn('Stop command timed out, forcing state reset.');
          return;
        }
        throw TimeoutException('Operation "$description" timed out');
      },
    );
  }

  /// Queues [prompt] for generation.
  ///
  /// [grammarStr] optionally constrains *this* generation to a GBNF grammar,
  /// without reloading the model: `null` (the default) keeps whatever grammar
  /// the load-time [SamplerParams] carried — byte-for-byte the previous
  /// behaviour — `''` explicitly drops it, and a GBNF string constrains this
  /// one prompt. [grammarRoot] names the grammar's root rule and defaults to
  /// the conventional `root`.
  ///
  /// A grammar llama.cpp cannot compile is non-fatal: generation proceeds
  /// unconstrained and the reason arrives as `errorDetails` on the
  /// [CompletionEvent] (with `success` still true).
  Future<String> sendPrompt(String prompt,
      {Object? scope, String? grammarStr, String? grammarRoot}) async {
    if (loadCommand.contextParams.embeddings) {
      throw StateError("Configured for embeddings only.");
    }
    final queuedPrompt = _QueuedPrompt(prompt, scope,
        grammarStr: grammarStr, grammarRoot: grammarRoot);
    _promptQueue.add(queuedPrompt);
    if (!_isProcessingQueue) _processNextPrompt();
    return queuedPrompt.idCompleter.future;
  }

  /// As [sendPrompt], with images. See [sendPrompt] for the grammar contract.
  Future<String> sendPromptWithImages(String prompt, List<LlamaImage> images,
      {Object? scope, String? grammarStr, String? grammarRoot}) async {
    if (loadCommand.contextParams.embeddings) {
      throw StateError("Configured for embeddings only.");
    }
    final queuedPrompt = _QueuedPrompt(prompt, scope,
        images: images, grammarStr: grammarStr, grammarRoot: grammarRoot);
    _promptQueue.add(queuedPrompt);
    if (!_isProcessingQueue) _processNextPrompt();
    return queuedPrompt.idCompleter.future;
  }

  Future<void> _processNextPrompt() async {
    if (_promptQueue.isEmpty) {
      _isProcessingQueue = false;
      return;
    }

    _isProcessingQueue = true;
    final nextPrompt = _promptQueue.removeAt(0);

    if (_isGenerating) {
      // Cancel the in-flight generation, then wait for the child to actually
      // emit isDone for the previous prompt before queuing the next one.
      // The previous fork used a 10ms Future.delayed here, which raced on slow
      // devices: the next LlamaPrompt could land while the child was still
      // draining the prior generation, causing tokens to be tagged with the
      // wrong promptId.
      final previousPromptId = _currentPromptId;
      await stop();
      final previousCompleter = _promptCompleters[previousPromptId];
      if (previousCompleter != null && !previousCompleter.isCompleted) {
        try {
          await previousCompleter.future
              .timeout(const Duration(seconds: 2));
        } catch (_) {
          // Best-effort drain; proceed even if the prior prompt never
          // confirmed completion (worst case the child has already moved on).
        }
      }
    }

    _currentPromptId = DateTime.now().millisecondsSinceEpoch.toString();
    _promptCompleters[_currentPromptId] = Completer<void>();

    _currentScope = nextPrompt.scope;

    String? targetSlotId;
    if (nextPrompt.scope != null && nextPrompt.scope is LlamaScope) {
        targetSlotId = (nextPrompt.scope as LlamaScope).id;
        (nextPrompt.scope as LlamaScope).addPromptId(_currentPromptId);
    }

    final formattedPrompt = messages.isEmpty
        ? (formatter?.formatPrompt(nextPrompt.prompt) ?? nextPrompt.prompt)
        : (formatter?.formatMessages(messages) ?? nextPrompt.prompt);

    // Expose promptId only after prompt formatting is finalized. This avoids a
    // race where callers mutate `messages` immediately after awaiting sendPrompt,
    // before the queue worker has consumed them.
    nextPrompt.idCompleter.complete(_currentPromptId);

    _isGenerating = true;
    _status = LlamaStatus.generating;

    _parent.sendToChild(
        id: 1,
        data: LlamaPrompt(formattedPrompt, _currentPromptId,
            images: nextPrompt.images,
            slotId: targetSlotId,
            grammarStr: nextPrompt.grammarStr,
            grammarRoot: nextPrompt.grammarRoot));

    _promptCompleters[_currentPromptId]!.future.whenComplete(() {
      _processNextPrompt();
    });
  }

  Future<void> waitForCompletion(String promptId) async {
    if (!_promptCompleters.containsKey(promptId)) return;
    final completer = _promptCompleters[promptId]!;
    await completer.future;
  }

  Future<void> stop() async {
    if (_isGenerating) {
      await _sendCommand(LlamaStop(), "generation stopping");
      _isGenerating = false;
    }
  }

  /// Clears the KV cache and resets the context without unloading the model.
  /// Use this to recover memory after a native inference error.
  Future<void> clear() async {
    if (_status != LlamaStatus.disposed) {
      await _sendCommand(LlamaClear(), "context clear");
    }
  }

  Future<List<double>> getEmbeddings(String prompt) async {
    if (!loadCommand.contextParams.embeddings) {
      throw StateError("Not configured for embeddings.");
    }
    _embeddingsCompleter = Completer();
    _parent.sendToChild(id: 1, data: LlamaEmbedd(prompt));
    return _embeddingsCompleter!.future;
  }

  /// Counts tokens for [text] using the loaded model's real tokenizer.
  /// Vocab-only — no inference and no KV-cache interaction, so it is cheap
  /// and safe to call between generations (callers should avoid calling it
  /// while a generation is streaming; the child processes commands
  /// sequentially, so the count would be delayed, not corrupted).
  Future<int> countTokens(String text, {bool addBos = true}) async {
    _tokenizeCompleter = Completer<int>();
    _parent.sendToChild(id: 1, data: LlamaTokenizeCount(text, addBos: addBos));
    return _tokenizeCompleter!.future.timeout(
      const Duration(seconds: 10),
      onTimeout: () {
        _tokenizeCompleter = null;
        throw TimeoutException("countTokens timed out");
      },
    );
  }

  Future<void> dispose() async {
    _isGenerating = false;
    _status = LlamaStatus.disposed;

    if (_readyCompleter != null && !_readyCompleter!.isCompleted) _readyCompleter!.completeError("Disposed");
    if (_operationCompleter != null && !_operationCompleter!.isCompleted) _operationCompleter!.completeError("Disposed");
    if (_embeddingsCompleter != null && !_embeddingsCompleter!.isCompleted) _embeddingsCompleter!.completeError("Disposed");
    if (_tokenizeCompleter != null && !_tokenizeCompleter!.isCompleted) _tokenizeCompleter!.completeError("Disposed");
    if (_stateCompleter != null && !_stateCompleter!.isCompleted) _stateCompleter!.completeError("Disposed");

    for (var p in _promptQueue) {
      if (!p.idCompleter.isCompleted) p.idCompleter.completeError("Disposed");
    }
    _promptQueue.clear();

    for (final scope in List.from(_scopes)) {
      await scope.dispose();
    }
    _scopes.clear();

    // Tell the child to dispose, give it a brief moment to flush any final
    // confirmations, THEN cancel the subscription, THEN close the controllers.
    // The previous order closed controllers first, which caused
    // "Cannot add new events after calling close" when the child emitted any
    // late tokens or the dispose acknowledgement during the drain window.
    _parent.sendToChild(id: 1, data: LlamaDispose());
    await Future.delayed(const Duration(milliseconds: 50));
    await _subscription?.cancel();

    if (!_controller.isClosed) await _controller.close();
    if (!_completionController.isClosed) await _completionController.close();

    _parent.dispose();
  }

  dynamic getScope() {
    final scope = LlamaScope(this);
    _scopes.add(scope);
    return scope;
  }

  Future<void> cancelScope(Object scope,
      {bool cancelInFlight = true, bool cancelQueued = true}) async {
    if (cancelQueued) {
      _promptQueue.removeWhere((p) {
        if (identical(p.scope, scope)) {
          if (!p.idCompleter.isCompleted) {
            p.idCompleter.completeError("Scope canceled");
          }
          return true;
        }
        return false;
      });
    }
    if (cancelInFlight && identical(_currentScope, scope) && _isGenerating) {
      await stop();
    }
  }
}
